name: deployment pratice
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm ci

      - name: run the lint 
        run: npm run lint

      - name: test the code
        run: npm run test

      

  deploye:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm ci

      - name: run the lint 
        run: npm run lint

      - name: build the project
        run: npm run build

      - name: upload the build to artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: distribute file
          path: dist

      - name: delpoye the project
        run: echo "Deploying..."

  download:
    needs: deploye
    runs-on: ubuntu-latest
    steps:
      - name: Get the uploaded artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: distribute file

      - name: listout the files
        run: ls

     
